name: Update contact information
description: Update the contact information for the method as the existing ID is no longer reachable.
title: "Update contact information"

body:
  - type: input
    id: title
    attributes:
      label: Methods Hub method title
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: Methods Hub method url
      description: Provide the GitHub repository URL for the method.
      placeholder: "https://github.com/organization/repository"
    validations:
      required: true
