name: Update contact information
description: Request an update to the contact information for a method/tutorial when the existing contact is no longer reachable.
title: "Update contact information"

body:
  - type: input
    id: title
    attributes:
      label: Methods Hub method/tutorial title
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Methods Hub method/tutorial link
      description: Provide the GitHub repository where the method/tutorial is maintained.
      placeholder: "https://github.com/organization/repository"
    validations:
      required: true

  - type: textarea
    id: reviewer
    attributes:
      label: Reviewer
      value: |
        Link this issue in the method/tutorial repository issue with the outdated contact information.
      render: markdown

  - type: textarea
    id: developer
    attributes:
      label: Developer
      value: |
        Update the contact information in the method/tutorial repository, close the repository issue, and respond to the main issue linked there.
      render: markdown
